import { eq } from 'drizzle-orm';
import { ShareViewer } from './ShareViewer';
import { BrandedUnavailableState } from '@/components/viewers/BrandedViewerScaffold';
import type { Metadata } from 'next';

interface SharePageProps {
  params: Promise<{ id: string }>;
}

async function getShareDb() {
  const [{ db }, { shareLinks }] = await Promise.all([import('@/db'), import('@/db/schema')]);

  return { db, shareLinks };
}

export async function generateMetadata({ params }: SharePageProps): Promise<Metadata> {
  const { id } = await params;

  try {
    const { db, shareLinks } = await getShareDb();
    const link = await db.query.shareLinks.findFirst({
      where: eq(shareLinks.id, id),
    });

    if (!link) return { title: 'Share Link Not Found' };

    return {
      title: `Synesthesia — Shared Artwork (${link.styleName})`,
      description: 'View a shared artwork generated by the Synesthesia Machine.',
    };
  } catch {
    return {
      title: 'Share Link Unavailable',
      description: 'Share links require a configured database backend.',
    };
  }
}

/**
 * /share/[id] — Server Component
 *
 * Fetches share link data from the database and renders ShareViewer.
 * Never exposes raw input text (SHARE-02, SHARE-03).
 */
export default async function SharePage({ params }: SharePageProps) {
  const { id } = await params;

  try {
    const { db, shareLinks } = await getShareDb();
    const link = await db.query.shareLinks.findFirst({
      where: eq(shareLinks.id, id),
    });

    if (!link) {
      return (
        <BrandedUnavailableState
          title="Share viewer unavailable"
          description="This share link may have expired, been removed, or is unavailable in the current local proof mode."
          diagnosticLabel="Missing share id"
          diagnosticMessage={id}
        />
      );
    }

    return (
      <ShareViewer
        parameterVector={link.parameterVector}
        versionInfo={link.versionInfo}
        styleName={link.styleName}
        createdAt={link.createdAt.toISOString()}
      />
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Share backend unavailable';

    return (
      <BrandedUnavailableState
        title="Share viewer unavailable"
        description="This shared route needs a working database backend in the current environment."
        diagnosticLabel="Diagnostics"
        diagnosticMessage={message}
      />
    );
  }
}
