import { db } from '@/db';
import { shareLinks } from '@/db/schema';
import { eq } from 'drizzle-orm';
import { ShareViewer } from './ShareViewer';
import type { Metadata } from 'next';

interface SharePageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { id } = await params;
  const link = await db.query.shareLinks.findFirst({
    where: eq(shareLinks.id, id),
  });
  if (!link) return { title: 'Share Link Not Found' };
  return {
    title: `Synesthesia — Shared Artwork (${link.styleName})`,
    description: 'View a shared artwork generated by the Synesthesia Machine.',
  };
}

/**
 * /share/[id] — Server Component
 *
 * Fetches share link data from the database and renders ShareViewer.
 * Never exposes raw input text (SHARE-02, SHARE-03).
 */
export default async function SharePage({ params }: SharePageProps) {
  const { id } = await params;

  const link = await db.query.shareLinks.findFirst({
    where: eq(shareLinks.id, id),
  });

  if (!link) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-semibold mb-2">Share Link Not Found</h1>
          <p className="text-muted-foreground">
            This share link may have been removed or does not exist.
          </p>
        </div>
      </div>
    );
  }

  return (
    <ShareViewer
      parameterVector={link.parameterVector}
      versionInfo={link.versionInfo}
      styleName={link.styleName}
      createdAt={link.createdAt.toISOString()}
    />
  );
}
