import { GalleryViewer } from './GalleryViewer';
import { BrandedUnavailableState } from '@/components/viewers/BrandedViewerScaffold';
import { classifyObservabilityError } from '@/lib/observability/privacy';
import type { Metadata } from 'next';

interface GalleryDetailPageProps {
  params: Promise<{ id: string }>;
}

async function getGalleryDb() {
  return import('@/lib/gallery/db-gallery');
}

export async function generateMetadata({ params }: GalleryDetailPageProps): Promise<Metadata> {
  const { id } = await params;

  try {
    const { getGalleryItem } = await getGalleryDb();
    const item = await getGalleryItem(id);
    if (!item) return { title: 'Gallery Item Not Found' };
    return {
      title: `${item.title ?? 'Artwork'} — Synesthesia Gallery`,
      description: `A ${item.styleName} artwork generated by the Synesthesia Machine.`,
    };
  } catch {
    return {
      title: 'Gallery Unavailable',
      description: 'Gallery detail pages require a configured database backend.',
    };
  }
}

/**
 * /gallery/[id] — Server Component (GAL-06).
 * Fetches the gallery item and passes to GalleryViewer client component.
 * Mirrors the /share/[id] pattern from Phase 7.
 */
export default async function GalleryDetailPage({ params }: GalleryDetailPageProps) {
  const { id } = await params;

  try {
    const { getGalleryItem } = await getGalleryDb();
    const item = await getGalleryItem(id);

    if (!item) {
      return (
        <BrandedUnavailableState
          title="Gallery viewer unavailable"
          description="This gallery edition may have been removed or is unavailable in the current local proof mode."
          diagnosticLabel="Missing gallery id"
          diagnosticMessage={id}
          observability={{
            routeFamily: 'gallery',
            unavailableCategory: 'missing-resource',
            statusBucket: '4xx',
            viewerSurface: 'detail',
          }}
        />
      );
    }

    return (
      <GalleryViewer
        id={item.id}
        parameterVector={item.parameterVector}
        versionInfo={item.versionInfo}
        styleName={item.styleName}
        title={item.title ?? null}
        inputPreview={item.inputPreview ?? null}
        createdAt={item.createdAt.toISOString()}
        upvoteCount={item.upvoteCount}
      />
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Gallery backend unavailable';
    const category = classifyObservabilityError(error);

    return (
      <BrandedUnavailableState
        title="Gallery viewer unavailable"
        description="This collector route needs a working database backend in the current environment."
        diagnosticLabel="Diagnostics"
        diagnosticMessage={message}
        observability={{
          routeFamily: 'gallery',
          unavailableCategory:
            category === 'local-proof-unavailable' ? 'local-proof-unavailable' : 'backend-unavailable',
          statusBucket: '5xx',
          localProofMode: category === 'local-proof-unavailable',
          viewerSurface: 'detail',
        }}
      />
    );
  }
}
