import { getGalleryItem } from '@/lib/gallery/db-gallery';
import { GalleryViewer } from './GalleryViewer';
import type { Metadata } from 'next';

interface GalleryDetailPageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: GalleryDetailPageProps): Promise<Metadata> {
  const { id } = await params;
  const item = await getGalleryItem(id);
  if (!item) return { title: 'Gallery Item Not Found' };
  return {
    title: `${item.title ?? 'Artwork'} — Synesthesia Gallery`,
    description: `A ${item.styleName} artwork generated by the Synesthesia Machine.`,
  };
}

/**
 * /gallery/[id] — Server Component (GAL-06).
 * Fetches the gallery item and passes to GalleryViewer client component.
 * Mirrors the /share/[id] pattern from Phase 7.
 */
export default async function GalleryDetailPage({ params }: GalleryDetailPageProps) {
  const { id } = await params;
  const item = await getGalleryItem(id);

  if (!item) {
    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-semibold mb-2">Gallery Item Not Found</h1>
          <p className="text-muted-foreground">This item may have been removed.</p>
        </div>
      </div>
    );
  }

  return (
    <GalleryViewer
      id={item.id}
      parameterVector={item.parameterVector}
      versionInfo={item.versionInfo}
      styleName={item.styleName}
      title={item.title ?? null}
      inputPreview={item.inputPreview ?? null}
      createdAt={item.createdAt.toISOString()}
      upvoteCount={item.upvoteCount}
    />
  );
}
