import { GalleryGrid } from '@/components/gallery/GalleryGrid';
import { Shell } from '@/components/layout/Shell';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Gallery — Synesthesia Machine',
  description: 'Browse artwork generated by the Synesthesia Machine.',
};

interface GalleryPageProps {
  searchParams: Promise<{
    style?: string;
    sort?: string;
    page?: string;
  }>;
}

async function getGalleryDb() {
  return import('@/lib/gallery/db-gallery');
}

/**
 * /gallery — Server Component
 *
 * Fetches gallery items from DB with optional style filter and sort.
 * Renders GalleryGrid (client) with the fetched items.
 */
export default async function GalleryPage({ searchParams }: GalleryPageProps) {
  const { style, sort, page } = await searchParams;
  const pageNum = Math.max(1, parseInt(page || '1'));
  const limit = 20;
  const offset = (pageNum - 1) * limit;

  const validSort = sort === 'popular' ? 'popular' : 'recent';
  const validStyle = ['geometric', 'organic', 'particle', 'typographic'].includes(style ?? '')
    ? style
    : undefined;

  try {
    const { getGalleryItems } = await getGalleryDb();
    const items = await getGalleryItems({
      style: validStyle,
      sort: validSort,
      limit,
      offset,
    });

    return (
      <Shell currentRoute="gallery">
        <section className="editorial-stage space-y-8" aria-labelledby="gallery-browse-title">
          <div className="space-y-6 max-w-4xl">
            <div className="editorial-kicker">Route intro</div>
            <div className="space-y-4">
              <h1 id="gallery-browse-title" className="editorial-display text-4xl sm:text-5xl lg:text-6xl leading-[0.94]">
                Gallery browse
              </h1>
              <p className="max-w-2xl text-base sm:text-lg text-[var(--foreground)]/88 leading-relaxed">
                A public collector route inside the same editorial product family.
              </p>
              <p className="max-w-3xl text-sm sm:text-base text-[var(--muted-foreground)] leading-relaxed">
                Review public opt-in editions, filter by renderer family, and move through the archive with the same route-discovery language used by Home and Compare.
              </p>
            </div>
            <div className="editorial-marquee" aria-label="Gallery browse traits">
              <span>Public opt-ins only · viewer-safe metadata</span>
              <span>collector rhythm</span>
              <span>shared shell continuity</span>
            </div>
          </div>

          <GalleryGrid
            items={items}
            currentStyle={validStyle}
            currentSort={validSort}
            currentPage={pageNum}
            hasMore={items.length === limit}
          />
        </section>
      </Shell>
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Gallery backend unavailable';

    return (
      <Shell currentRoute="gallery">
        <section className="editorial-stage max-w-3xl" aria-labelledby="gallery-unavailable-title">
          <div className="editorial-panel editorial-control-surface space-y-6">
            <div className="space-y-3">
              <p className="editorial-note-label">Unavailable state</p>
              <h1 id="gallery-unavailable-title" className="editorial-display text-4xl sm:text-5xl leading-[0.96]">
                Gallery unavailable
              </h1>
              <p className="max-w-2xl text-sm sm:text-base text-[var(--muted-foreground)] leading-relaxed">
                The collector archive could not be loaded in this local proof mode.
              </p>
            </div>

            <div className="editorial-support-panel space-y-2">
              <p className="text-sm font-medium text-[var(--foreground)]">Diagnostics</p>
              <p className="text-sm text-[var(--muted-foreground)] leading-relaxed">{message}</p>
            </div>
          </div>
        </section>
      </Shell>
    );
  }
}
