import { GalleryGrid } from '@/components/gallery/GalleryGrid';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Gallery — Synesthesia Machine',
  description: 'Browse artwork generated by the Synesthesia Machine.',
};

interface GalleryPageProps {
  searchParams: Promise<{
    style?: string;
    sort?: string;
    page?: string;
  }>;
}

async function getGalleryDb() {
  return import('@/lib/gallery/db-gallery');
}

/**
 * /gallery — Server Component
 *
 * Fetches gallery items from DB with optional style filter and sort.
 * Renders GalleryGrid (client) with the fetched items.
 */
export default async function GalleryPage({ searchParams }: GalleryPageProps) {
  const { style, sort, page } = await searchParams;
  const pageNum = Math.max(1, parseInt(page || '1'));
  const limit = 20;
  const offset = (pageNum - 1) * limit;

  const validSort = sort === 'popular' ? 'popular' : 'recent';
  const validStyle = ['geometric', 'organic', 'particle', 'typographic'].includes(style ?? '')
    ? style
    : undefined;

  try {
    const { getGalleryItems } = await getGalleryDb();
    const items = await getGalleryItems({
      style: validStyle,
      sort: validSort,
      limit,
      offset,
    });

    return (
      <div className="min-h-screen bg-background text-foreground">
        <div className="max-w-6xl mx-auto p-6">
          <header className="mb-8">
            <h1 className="text-3xl font-semibold tracking-tight">Gallery</h1>
            <p className="text-muted-foreground mt-1">
              Artwork generated by the Synesthesia Machine. All entries are public opt-ins.
            </p>
          </header>

          <GalleryGrid
            items={items}
            currentStyle={validStyle}
            currentSort={validSort}
            currentPage={pageNum}
            hasMore={items.length === limit}
          />
        </div>
      </div>
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Gallery backend unavailable';

    return (
      <div className="min-h-screen bg-background text-foreground flex items-center justify-center">
        <div className="text-center max-w-lg px-6">
          <h1 className="text-3xl font-semibold tracking-tight mb-2">Gallery Unavailable</h1>
          <p className="text-muted-foreground">{message}</p>
        </div>
      </div>
    );
  }
}
